@startuml docs-v2

skinparam linetype ortho

package ユーザ {
    entity ユーザ {
        * ユーザID
        ---
        ユーザ名
    }
}

package ドキュメント {
    entity ドキュメント {
        * ドキュメントID
        ---
    }

    entity 下書きドキュメント {
        下書きドキュメントID
        ---
        + ドキュメントID [FK]
        文書内容
        作成日
    }

    entity 公開ドキュメント {
        公開ドキュメントID
        ---
        + ドキュメントID [FK]
        文書内容
        公開日
    }

    entity 削除ドキュメント {
        削除ドキュメントID
        ---
        + ドキュメントID [FK]
        文書内容
        削除日
    }

    entity ドキュメント所有 {
        * ユーザID [FK]
        * ドキュメントID [FK]
    }

    entity ドキュメント場所 {
        * ディレクトリID [FK]
        * ドキュメントID [FK]
    }

    ユーザ ||-r-o{ ドキュメント所有
    ドキュメント ||-l-|{ ドキュメント所有
    ディレクトリ ||-l-o{ ドキュメント場所
    ドキュメント ||-r-|{ ドキュメント場所

    ドキュメント ||--|| 下書きドキュメント
    ドキュメント ||--|| 公開ドキュメント
    ドキュメント ||--|| 削除ドキュメント
}

package ディレクトリ {
    entity ディレクトリ {
        * ディレクトリID
        --
        ディレクトリ名
    }

    entity ディレクトリ構造 {
        * 親ディレクトリID [FK]
        * 子ディレクトリID [FK]
    }

    ディレクトリ ||--|{ ディレクトリ構造
    ディレクトリ ||--|{ ディレクトリ構造
}

@enduml