@startuml docs

skinparam linetype ortho

package ユーザ {
    entity ユーザ {
        * ユーザID
        ---
        ユーザ名
    }
}

package ドキュメント {
    entity ドキュメント {
        * ドキュメントID
        ---
        文書内容
        文書ステータス
        + ディレクトリID [FK]
        + ユーザID [FK]
    }
}

package ディレクトリ {
    entity ディレクトリ {
        * ディレクトリID
        --
        ディレクトリ名
    }

    entity ディレクトリ構造 {
        * 親ディレクトリID [FK]
        * 子ディレクトリID [FK]
    }

    ディレクトリ ||--|{ ディレクトリ構造
    ディレクトリ ||--|{ ディレクトリ構造
}

ユーザ ||-ri-o{ ドキュメント
ドキュメント }o-ri-|| ディレクトリ

@enduml