@startuml docs

skinparam linetype ortho

entity User {
    * user_id
    ---
    name
}

entity UserOwnDocument {
    * user_id
    * document_id
}

entity Document {
    * document_id
    ---
    created_at
    contents
}

entity DocumentTree {
    * ancestor_id
    * desccendant_id
}

@enduml