@startuml settings

skinparam Linetype ortho
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

package 顧客マスタ {
    entity 顧客 <<M,MASTER_MARK_COLOR>> {
        * 顧客ID
        --
        お名前
        電話番号
    }
}

package 税マスタ {
    entity 消費税区分 <<M,MASTER_MARK_COLOR>> {
        * 消費税区分ID
        --
        消費税区分名
    }

    entity 税率区分 <<M,MASTER_MARK_COLOR>> {
        * 税率区分
        --
        適用開始日
        適用終了日
        消費税区分ID [FK]
        税率
    }

    消費税区分 ||--|{ 税率区分
}

package 商品マスタ {
    entity 単品商品 <<M,MASTER_MARK_COLOR>> {
        * 単品商品ID
        --
        商品名
        商品種別ID [FK]
        消費税区分ID [FK]
    }

    entity 単品商品種別 <<M,MASTER_MARK_COLOR>> {
        * 商品種別ID
        --
        単品商品種別名
        単価
    }

    entity セット商品 <<M,MASTER_MARK_COLOR>> {
        * セット商品ID
        --
        商品名
        単価
    }

    entity セット商品種別 <<M,MASTER_MARK_COLOR>> {
        * セット商品種別ID
        --
        セット商品種別名
    }

    単品商品 |o--|| 単品商品種別
    セット商品 |o--|| セット商品種別
}

package 注文管理 {
    entity 注文 <<T,TRANSACTION_MARK_COLOR>> {
        * 注文ID
        --
        顧客ID [FK]
        注文日時
        支払い済みフラグ
    }

    entity 単品注文明細 <<T,TRANSACTION_MARK_COLOR>> {
        * 注文ID [FK]
        * 単品商品ID [FK]
        --
        皿数
        わさびあり
        税率ID [FK]
    }

    entity セット注文明細 <<T,TRANSACTION_MARK_COLOR>> {
        * 注文ID [FK]
        * セット商品ID [FK]
        --
        個数
        わさびあり
        税率ID [FK]
    }

    注文 ||-do-o{ 単品注文明細
    注文 ||-do-o{ セット注文明細
}

@enduml