@startuml chat-v1

skinparam linetype ortho

entity User {
    * id
    ---
    name
}

entity Workspace {
    * id
    ---
    name
}

entity Channel {
    * id
    ---
    name
    workspace_id [FK]
}

entity Workspace_Member {
    * user_id [FK]
    * workspace_id [FK]
}

entity Channel_Member {
    * user_id
    * channel_id
}

entity Channel_Thread_Message {
    * user_id [FK]
    * channel_id [FK]
    --
    message
    sent_at
    is_thread
}

entity MessageTree {
    * ancestor_id
    * descendant_id
}

Workspace ||--|{ Channel
User ||-u-o{ Workspace_Member
Workspace ||--|{ Workspace_Member
User ||-r-o{ Channel_Member
Channel ||-l-|{ Channel_Member
User ||--o{ Channel_Thread_Message
Channel ||--o{ Channel_Thread_Message
Channel_Thread_Message ||--o{ MessageTree
Channel_Thread_Message ||--o{ MessageTree

@enduml
