@startuml chat

skinparam linetype ortho

entity User {
    * id
    ---
    name
}

entity Channel {
    * id
    ---
    name
    workspace_id [FK]
}

entity Workspace {
    * id
    ---
    description
}

entity Workspace_User_Type {
    * id
    --
    type
}

entity Workspace_Member {
    * user_id [FK]
    * workspace_id [FK]
    --
    user_type [FK]
}

entity Channel_Member {
    * user_id
    * channel_id
}

entity Channel_Thread {
    * id
    --
    channel_id [FK]
}

entity Channel_Thread_Message {
    * user_id [FK]
    * channel_thread_id [FK]
}

@enduml
