@startuml chat-v1

skinparam linetype ortho

package ユーザ {
    entity ユーザ {
        * ユーザID
        ---
        ユーザ名
    }

    entity ワークスペース所属 {
        * ユーザID [FK]
        * ワークスペースID [FK]
        --
        ユーザステータス
    }

    entity チャンネル所属 {
        * ユーザID [FK]
        * チャンネルID [FK]
        --
        ユーザステータス
    }
}

package ワークスペース構造 {
    entity ワークスペース {
        * ワークスペースID
        ---
        ワークスペース名
    }

    entity チャンネル {
        * チャンネルID
        ---
        チャンネル名
        ワークスペースID [FK]
    }
}

package メッセージ {
    entity メッセージ {
        * メッセージID
        --
        + ユーザID [FK]
        + チャンネルID [FK]
        投稿内容
        投稿日時
        スレッドフラグ
    }

    entity メッセージ関係 {
        * 親メッセージID [FK]
        * 子メッセージID [FK]
    }
}

ワークスペース ||--|{ チャンネル
ユーザ ||-u-o{ ワークスペース所属
ワークスペース ||--|{ ワークスペース所属
ユーザ ||-r-o{ チャンネル所属
チャンネル ||-l-|{ チャンネル所属
ユーザ ||--o{ メッセージ
チャンネル ||--o{ メッセージ
メッセージ ||--o{ メッセージ関係
メッセージ ||--o{ メッセージ関係

@enduml
