@startuml penpen-v1

skinparam Linetype ortho

package ユーザ {
    entity ユーザ {
        * ユーザID
        --
        ユーザ名
    }
}

package リマインダー {
    entity リマインダー {
        * リマインダーID
        --
        文面
        作成ユーザID [FK]
    }

    entity リマインド周期 {
        * リマインド周期ID
        --
        周期期間
    }

    entity リマインドユーザ {
        * リマインドID
        * ユーザID
        --
        タスクステータス
    }
}

リマインダー ||--|{ リマインドユーザ
ユーザ ||-r-o{ リマインドユーザ
ユーザ ||-r-o{ リマインダー

@enduml