@startuml domainModel

/'
  集約: packages
  オブジェクト: objects
  メモ: notes
  関連: * → コンポジッション (インスタンス参照)
        > → 集約間の連携 (ID参照)
  多重度: "<>" -()- "<>"
'/

skinparam PackageStyle rectangle
' skinparam Linetype ortho

note as 仕様
    ①ペアやチームの編成は、
    承諾を得ることなく
    管理者が変更できる

    ②ステータスの変更は、
    管理者が承諾なく実施できる
end note

package ユーザー集約 {
    object 参加者 {
        参加者ID
        名前
        メールアドレス
        在籍ステータス
        + 課題ID
    }

    note left of 参加者 
        ①メールアドレスの重複は許容しない

        ②在籍ステータスは下記3種類
        「在籍中」「休会中」「退会済」
        
        ③「在籍中」以外の場合は、
        どのペアにも
        どのチームにも所属しない
    end note
}

package チーム集約 {
    object チーム {
        チームID
        チーム名
        + ペアID
    }

    note left of チーム
        ①チーム名は [0-9]{1,3} の条件を満たす

        ②最低でも3名の参加者が必要となる

        ③参加者の上限はなし

        ③チームから参加者が減る場合 (移動、退会など)
            ○2名以下の場合は、最も参加者が少ないチームが
                自動的に選択される
            ○最小人数のチームが複数ある場合は
                その中からランダムに選択される

        ④チームに参加者が増える場合
            ○参加者の上限数はなし
            ○ステータスが「在籍中」に変更された場合
                最も少ない人数のチーム、ペアが
                自動敵に選択される
    end note

    object ペア {
        ペアID
        ペア名
        + 参加者ID
    }

    note right of ペア
        ①ペア名は [a-z]{1} を満たす
        
        ②参加者は2~3名で構成される

        ③ペアから参加者が減る場合
            ○1名になった場合、最も人数の少ないペアが
                自動的に選択される
            ○最少人数のペアが複数ある場合は
                その中からランダムに選択される

        ④ペアに参加者が増える場合
            ○参加者が4名に増えた段階でペアを分割し
                参加者数が最も少ない他のペアに移動
    end note
}

ペア -left-> チーム
参加者 "2..3" -down-> "0..1" ペア

package 課題集約 {
    object 課題 {
        課題ID
        課題名
        課題内容
        進捗ステータス
    }

    note left of 課題
        ①参加者はそれぞれ課題を80個程度所有する

        ②以下の進捗ステータスを有する
        「未着手」「着手中」「レビュー待ち」「完了」

        ③進捗ステータスはいつでも変更可能

        ④一度進捗ステータスが「完了」になると
        ほかのステータスに変更できない

        ⑤進捗ステータスを変更できるのは、
        課題の所有者だけである
    end note
}


参加者 "1..n" <-u- "1..80" 課題

@enduml