@startuml ER

/'
  集約: packages
  オブジェクト: objects
  メモ: notes
  関連: * → コンポジッション (インスタンス参照)
        > → 集約間の連携 (ID参照)
  多重度: "<>" -()- "<>"
'/

skinparam PackageStyle rectangle
skinparam Linetype ortho

package 課題 {
    entity 課題 {
        課題ID
        ---
        課題名
        課題内容
    }

    entity 課題ステータス {
        課題ステータスID
        ---
        ステータス名
    }

    note bottom of 課題ステータス
        課題ステータスは3種
        ●未着手
        ●着手中
        ●レビュー待ち
        ●完了
    end note

    entity 課題進捗 {
        + 課題ID
        + 参加者ID
        ---
        + 課題ステータスID
    }

    課題 ||--o{ 課題進捗
    課題ステータス ||-r-o{ 課題進捗
}

package ユーザー {
    entity 参加者 {
        参加者ID
        ---
        名前
        メールアドレス
        + 在籍ステータスID
    }

    entity 在籍ステータス {
        在籍ステータスID
        ---
        ステータス名
    }

    note right of 在籍ステータス
        在籍ステータスは3種
        ●在籍中
        ●休会中
        ●退会済
    end note

    参加者 ||-u-|| 在籍ステータス
}

package チーム {
    entity チーム {
        チームID
        ---
        チーム名
    }

    entity チーム所属 {
        + チームID
        + 参加者ID
    }

    チーム ||--o{ チーム所属
}

package ペア {
    entity ペア {
        ペアID
        ---
        ペア名
    }

    entity ペア所属 {
        + ペアID
        + 参加者ID
    }

    ペア ||-l-o{ ペア所属
}

参加者 ||-l-o{ 課題進捗
参加者 ||-r-o{ チーム所属
参加者 ||-d-o{ ペア所属

@enduml