@startuml domainModel

/'
  集約: packages
  オブジェクト: objects
  メモ: notes
  関連: * → コンポジッション (インスタンス参照)
        > → 集約間の連携 (ID参照)
  多重度: "<>" -()- "<>"
'/

skinparam PackageStyle rectangle
skinparam Linetype ortho

package ユーザー集約 {
    object 参加者 {
        参加者ID
        名前
        メールアドレス
        在籍ステータス
    }
}

note left of 参加者 
    ●メールアドレスの重複は許容しない
    ●以下の在籍ステータスを有する
       「在籍中」「休会中」「退会済」
    ●「在籍中」の場合はどのペアにも所属しない
end note

package チーム集約 {
    object チーム {
        チームID
        チーム名
        参加者ID
    }
}

note right of チーム
    ●チーム名は [0-9]{1,3} の条件を満たす
    ●最低でも3名の参加者が必要となる
end note

package ペア集約 {
    object ペア {
        ペアID
        ペア名
        参加者ID
    }
}

note bottom of ペア
    ペア名は [a-z]{1} を満たす
    参加者は2~3名で構成される
end note

@enduml