@startuml domainModel

/'
  集約: packages
  オブジェクト: objects
  メモ: notes
  関連: * → コンポジッション (インスタンス参照)
        > → 集約間の連携 (ID参照)
  多重度: "<>" -()- "<>"
'/

skinparam PackageStyle rectangle
' skinparam Linetype ortho

note as 仕様
    ●ステータスの変更は、ユーザーの承諾は不要
    ●チームから参加者が減る場合 (移動、退会など)
       ○2名以下の場合は、最も参加者が少ないチームが
          自動的に選択される
       ○最小人数のチームが複数ある場合は
          その中からランダムに選択される
       ○アプリケーションが自動的にチームを
          組み替えることができる
    ●チームに参加者が増える場合
       ○参加者の上限数はなし
       ○ステータスが「在籍中」に変更された場合
          最も少ない人数のチーム、ペアが
          自動敵に選択される
    ●ペアから参加者が減る場合
       ○1名になった場合、最も人数の少ないペアが
          自動的に選択される
       ○最少人数のペアが複数ある場合は
          その中からランダムに選択される
       ○アプリケーションが自動的にペアを
          組み替えることができる
    ●ペアに参加者が増える場合
       ○4名になった段階でペアを分割する
end note

package ユーザー集約 {
    object 参加者 {
        参加者ID
        名前
        メールアドレス
        在籍ステータス
    }
}

note left of 参加者 
    ●メールアドレスの重複は許容しない
    ●以下の在籍ステータスを有する
       「在籍中」「休会中」「退会済」
    ●「在籍中」の場合はどのペアにも
       どのチームにも所属しない
end note

package チーム集約 {
    object チーム {
        チームID
        チーム名
        参加者ID
    }
}

note bottom of チーム
    ●チーム名は [0-9]{1,3} の条件を満たす
    ●最低でも3名の参加者が必要となる
end note
参加者 "3..n" -down-> "0..1" チーム

package ペア集約 {
    object ペア {
        ペアID
        ペア名
        参加者ID
    }
}

note bottom of ペア
    ペア名は [a-z]{1} を満たす
    参加者は2~3名で構成される
end note
参加者 "2..3" -down-> "0..1" ペア

package 課題集約 {
    object 課題 {
        課題ID
        進捗ステータス
    }
}

note bottom of 課題
    ●参加者はそれぞれ課題を80個程度所有する
    ●以下の進捗ステータスを有する
       「未着手」「レビュー待ち」「完了」
    ●進捗ステータスはいつでも変更可能
    ●
end note
参加者 "1..n" <-- "1..80" 課題

@enduml