@startuml sushi

skinparam Linetype ortho
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

package 顧客マスタ {
    entity 顧客 <<M,MASTER_MARK_COLOR>> {
        * 顧客ID
        --
        お名前
        電話番号
    }
}

package 税率マスタ {
    entity 税率 <<M,MASTER_MARK_COLOR>> {
        * 税率ID
        --
        税率
    }
}

package 注文管理 {
    entity 注文 <<T,TRANSACTION_MARK_COLOR>> {
        * 注文ID
        --
        顧客ID [FK]
        注文日時
        支払い済みフラグ
    }

    entity 単品注文明細 <<T,TRANSACTION_MARK_COLOR>> {
        * 注文ID [FK]
        * 単品商品ID [FK]
        --
        皿数
        わさびあり
        税率ID [FK]
        シャリ種別ID [FK]
    }

    entity セット注文明細 <<T,TRANSACTION_MARK_COLOR>> {
        * 注文ID [FK]
        * セット商品ID [FK]
        --
        個数
        わさびあり
        税率ID [FK]
        シャリ種別ID [FK]
    }

    entity シャリ種別 <<M,MASTER_MARK_COLOR>> {
        * シャリ種別ID
        --
        シャリ種別名
    }

    注文 ||-do-o{ 単品注文明細
    注文 ||-do-o{ セット注文明細
    シャリ種別 }o-do-|| 単品注文明細
    シャリ種別 }o-do-|| セット注文明細
}

package 商品マスタ {
    entity 単品商品 <<M,MASTER_MARK_COLOR>> {
        * 単品商品ID
        --
        商品名
        商品種別ID [FK]
    }

    entity 単品商品種別 <<M,MASTER_MARK_COLOR>> {
        * 商品種別ID
        --
        単品商品種別名
        単価
    }

    entity セット商品 <<M,MASTER_MARK_COLOR>> {
        * セット商品ID
        --
        商品名
        単価
    }

    entity セット商品種別 <<M,MASTER_MARK_COLOR>> {
        * セット商品種別ID
        --
        セット商品種別名
    }

    entity セット商品構成 <<M,MASTER_MARK_COLOR>> {
        * 単品商品ID [FK]
        * セット商品ID [FK]
        --
        個数
    }

    単品商品 |o--|| 単品商品種別
    セット商品 |o--|| セット商品種別
    単品商品 ||-ri-o{ セット商品構成
    セット商品 ||-le-o{ セット商品構成
}

顧客 ||-le-o{ 注文
単品注文明細 }o-do-|| 単品商品
セット注文明細 }o-do-|| セット商品
単品注文明細 }o-ri-|| 税率
セット注文明細 }o-ri-|| 税率

@enduml