version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - '3001:5432'
    volumes:
      - dev-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'
    networks:
      - postgres
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '3002:80'
    volumes:
      - dev-pgadmin:/root/.pgadmin
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'
      PGADMIN_DEFAULT_EMAIL: dev@dev.com
      PGADMIN_DEFAULT_PASSWORD: dev
    networks:
      - postgres

volumes:
  dev-db:
    driver: local
  dev-pgadmin:
    driver: local

networks:
  postgres:
    driver: bridge
