@startuml delayID

participant Client
participant Product
participant ProductRepository
participant Database

activate Client

Client -> ProductRepository: nextIdentity()
activate ProductRepository

Client -> Product: new
activate Product

Client -> ProductRepository: add(aProduct)

ProductRepository -> Database: Insert
activate Database

ProductRepository -> Product: setProductId()

@enduml