### Register a User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "shimopino@example.com",
    "name": "shimopino",
    "password": "shimopino"
}

### Log In
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "shimopino@example.com",
    "password": "shimopino"
}