version: "3.9"
services: 
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "8080:8080"
    environment: 
      - PORT=8080
    # command: >
    #   bash -c "npx forever start app.js 
    #   && ngrok http -host-header='0.0.0.0:8080' 8080"
