@startuml sale-item

skinparam Linetype ortho

package 商品マスタ {
    entity 商品 {
        * 商品ID
        --
        商品名
        通常価格
        商品カテゴリID [FK]
        消費税区分ID [FK]
        セット商品区分
    }

    entity 商品カテゴリ {
        * 商品カテゴリID
        --
        カテゴリ名
    }

    entity セット商品構成 {
        * セット商品ID [FK]
        * 商品ID [FK]
        --
        個数
    }

    note bottom of セット商品構成
        セット商品IDには、
        商品マスタの中の
        セット商品区分が
        Trueの商品IDになる

        対象のセット商品IDが
        どの商品で構成されて
        いるのかを示す
    end note

    商品 }o--|| 商品カテゴリ
    商品 ||--o{ セット商品構成
    商品 ||--o{ セット商品構成
}

package セール {
    entity セール商品 {
        * 商品ID
        * セールイベントID
        --
        セール価格
    }

    entity セール {
        * セールイベントID
        --
        セール詳細
        セール開始日
        セール終了日
    }

    セール商品 }|--|| セール
}

商品 ||--o{ セール商品

@enduml