### Create a User
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "shimopino",
    "email": "shimopino@example.com",
    "password": "shimopino"
}

### Login a user
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "shimopino@example.com",
    "password": "shimopino"
}

### Check a login state
GET http://localhost:8080/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzaGltb3Bpbm9AZXhhbXBsZS5jb20iLCJpYXQiOjE2MzcxNzYwMjEsImV4cCI6MTYzNzE3OTYyMX0.ujBltYrFBdkR3vJC3MhWK2PzpbQ-jc_j2XMwOMNEFKY
